apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2hhcmJvci40LjI0Ny4xODAuNDEubmlwLmlvLyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJCaGFyZ2F2MTIzIiwiYXV0aCI6ImRkODUwOTQ3NzIxYWRjNzNlNjI4NmRlMjMwYmFhNGE0In19fQ==
