namespace: demo
targetCustomizations:
  - name: dev
    helm:
      values:
        replicaCount: 3
    clusterSelector:
      matchLabels:
        env: dev

  - name: prod
    helm:
      values:
        service:
          type: NodePort
        replicaCount: 2
    clusterSelector:
      matchLabels:
        env: prod
