namespace: demo
targetCustomizations:
  - name: dev
    helm:
      values:
        replicas: 2
    clusterSelector:
      matchLabels:
        env: dev

  - name: prod
    helm:
      values:
        serviceType: LoadBalancer
        replicas: 3
    clusterSelector:
      matchLabels:
        env: prod
