namespace: demo
targetCustomizations:
  - name: dev
    helm:
      values:
        replicaCount: 3
        image:
          tag: "1.0"
    clusterSelector:
      matchLabels:
        env: dev

  - name: prod
    helm:
      values:
        image:
          tag: "2.0"
        service:
          type: NodePort
        replicaCount: 2
    clusterSelector:
      matchLabels:
        env: prod
